# Package Documentation Template

> Copy this file for each package and fill using go-surgeon.

## Package `<PACKAGE_NAME>`

**Import path:** `<IMPORT_PATH>`

<!-- AGENT: Run go-surgeon graph --summary --dir <package_dir> -->

### Overview

_Package description from godoc comment._

### Types

<!-- AGENT: For each type from go-surgeon graph --symbols --dir <dir>:
     Run: go-surgeon symbol <TypeName> --body
     Then fill below -->

#### `TypeName`

```go
// Paste signature from: go-surgeon symbol TypeName
```

**Doc:** _Paste doc comment_

**Methods:**

| Method | Signature |
|--------|-----------|
| _Run `go-surgeon symbol TypeName.Method`_ | |

### Functions

<!-- AGENT: For each function from go-surgeon graph --symbols --dir <dir>:
     Run: go-surgeon symbol <FuncName> --body
     Then fill below -->

#### `FuncName`

```go
// Paste signature from: go-surgeon symbol FuncName
```

**Doc:** _Paste doc comment_

### Interfaces

<!-- AGENT: For each interface, use:
     go-surgeon symbol <InterfaceName> --body -->

---

*Generated by godoc-md template. Fill using go-surgeon symbol queries.*
